### ISSUE TITLE
Bluetooth crash

### ISSUE THREAD

**Issue by sakarya1980** [ValidusOs/Feature-List#1]
Navigon mobile Navigation crashes, when bluetooth is active and streaming the voice over Bluetooth car audio. One Google maps works perfect.

**Comment by Martinusbe** [comment]
got a log?

**Comment by fraz14** [comment]
which device?

**Comment by TheRingMaster** [comment]
Again logs?

**Comment by sakarya1980** [comment]
I have Oneplus 3. I have no log file anymore. I will reproduce these errors and then upload them

**Comment by sakarya1980** [comment]
[logcat.txt](https://github.com/ValidusOs/Feature-List/files/1374564/logcat.txt)

**Comment by Martinusbe** [comment]
leaving this here for later

10-11 09:12:17.065 10831 10831 E ActivityThread: Failed to find provider info for com.amazon.mas.client.framework.DeviceInfoCookieContentProvider
10-11 09:12:18.842   744  2038 I ActivityManager: START u0 {flg=0x4000000 cmp=de.amazon.mShop.android/com.amazon.venezia.AuthActivityToAliasInManifest (has extras)} from uid 10261
10-11 09:12:19.116 12562 12562 E ActivityThread: Activity com.navigon.navigator_select.hmi.MainMenuActivity has leaked IntentReceiver com.garmin.android.b.c.a$b@4abca72 that was originally registered here. Are you missing a call to unregisterReceiver()?
10-11 09:12:19.116 12562 12562 E ActivityThread: android.app.IntentReceiverLeaked: Activity com.navigon.navigator_select.hmi.MainMenuActivity has leaked IntentReceiver com.garmin.android.b.c.a$b@4abca72 that was originally registered here. Are you missing a call to unregisterReceiver()?
10-11 09:12:19.116 12562 12562 E ActivityThread: 	at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1333)
10-11 09:12:19.116 12562 12562 E ActivityThread: 	at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1114)
10-11 09:12:19.116 12562 12562 E ActivityThread: 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1405)
10-11 09:12:19.116 12562 12562 E ActivityThread: 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1378)
10-11 09:12:19.116 12562 12562 E ActivityThread: 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1366)
10-11 09:12:19.116 12562 12562 E ActivityThread: 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:603)
10-11 09:12:19.116 12562 12562 E ActivityThread: 	at com.garmin.android.b.c.a.c(ProGuard:700)
10-11 09:12:19.116 12562 12562 E ActivityThread: 	at com.garmin.android.b.c.a.a(ProGuard:130)
10-11 09:12:19.116 12562 12562 E ActivityThread: 	at com.garmin.android.b.a.c.e(ProGuard:74)
10-11 09:12:19.116 12562 12562 E ActivityThread: 	at com.garmin.android.b.a.c.a(ProGuard:39)
10-11 09:12:19.116 12562 12562 E ActivityThread: 	at com.navigon.navigator_select.hmi.hud.HudService.onBind(ProGuard:678)
10-11 09:12:19.116 12562 12562 E ActivityThread: 	at android.app.ActivityThread.handleBindService(ActivityThread.java:3431)
10-11 09:12:19.116 12562 12562 E ActivityThread: 	at android.app.ActivityThread.-wrap2(Unknown Source:0)
10-11 09:12:19.116 12562 12562 E ActivityThread: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
10-11 09:12:19.116 12562 12562 E ActivityThread: 	at android.os.Handler.dispatchMessage(Handler.java:105)
10-11 09:12:19.116 12562 12562 E ActivityThread: 	at android.os.Looper.loop(Looper.java:164)
10-11 09:12:19.116 12562 12562 E ActivityThread: 	at android.app.ActivityThread.main(ActivityThread.java:6541)
10-11 09:12:19.116 12562 12562 E ActivityThread: 	at java.lang.reflect.Method.invoke(Native Method)
10-11 09:12:19.116 12562 12562 E ActivityThread: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
10-11 09:12:19.116 12562 12562 E ActivityThread: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
10-11 09:12:19.119 12562 12562 E ActivityThread: Activity com.navigon.navigator_select.hmi.MainMenuActivity has leaked ServiceConnection com.navigon.navigator_select.hmi.hud.HudService$2@f417773 that was originally bound here
10-11 09:12:19.119 12562 12562 E ActivityThread: android.app.ServiceConnectionLeaked: Activity com.navigon.navigator_select.hmi.MainMenuActivity has leaked ServiceConnection com.navigon.navigator_select.hmi.hud.HudService$2@f417773 that was originally bound here
10-11 09:12:19.119 12562 12562 E ActivityThread: 	at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1514)
10-11 09:12:19.119 12562 12562 E ActivityThread: 	at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1406)
10-11 09:12:19.119 12562 12562 E ActivityThread: 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1589)
10-11 09:12:19.119 12562 12562 E ActivityThread: 	at android.app.ContextImpl.bindService(ContextImpl.java:1541)
10-11 09:12:19.119 12562 12562 E ActivityThread: 	at android.content.ContextWrapper.bindService(ContextWrapper.java:678)
10-11 09:12:19.119 12562 12562 E ActivityThread: 	at com.navigon.navigator_select.hmi.hud.HudService.a(ProGuard:468)
10-11 09:12:19.119 12562 12562 E ActivityThread: 	at com.navigon.navigator_select.hmi.MainMenuActivity.onCreateMainMenuActivity(ProGuard:3365)
10-11 09:12:19.119 12562 12562 E ActivityThread: 	at com.navigon.navigator_select.hmi.MainMenuActivity.onCreate(Unknown Source:0)
10-11 09:12:19.119 12562 12562 E ActivityThread: 	at android.app.Activity.performCreate(Activity.java:6975)
10-11 09:12:19.119 12562 12562 E ActivityThread: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
10-11 09:12:19.119 12562 12562 E ActivityThread: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
10-11 09:12:19.119 12562 12562 E ActivityThread: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
10-11 09:12:19.119 12562 12562 E ActivityThread: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
10-11 09:12:19.119 12562 12562 E ActivityThread: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
10-11 09:12:19.119 12562 12562 E ActivityThread: 	at android.os.Handler.dispatchMessage(Handler.java:105)
10-11 09:12:19.119 12562 12562 E ActivityThread: 	at android.os.Looper.loop(Looper.java:164)
10-11 09:12:19.119 12562 12562 E ActivityThread: 	at android.app.ActivityThread.main(ActivityThread.java:6541)
10-11 09:12:19.119 12562 12562 E ActivityThread: 	at java.lang.reflect.Method.invoke(Native Method)
10-11 09:12:19.119 12562 12562 E ActivityThread: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
10-11 09:12:19.119 12562 12562 E ActivityThread: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
10-11 09:12:19.120   744  2645 W ActivityManager: Unbind failed: could not find connection for android.os.BinderProxy@e7cbef
10-11 09:12:20.092 10831 10831 E ActivityThread: Failed to find provider info for com.amazon.mas.client.framework.DeviceInfoCookieContentProvider
10-11 09:12:21.337   744  6641 I Telecom : BluetoothPhoneService: getNetworkOperator: BPSI.gNO@AP4
10-11 09:12:22.132   744 13101 W DropBoxManagerService: Dropping: system_app_wtf (2251 > 0 bytes)
10-11 09:12:22.148   744 13102 W DropBoxManagerService: Dropping: system_app_wtf (2251 > 0 bytes)
